# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Recipe App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Recipe App
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Alamofire' # For getting images from URLs
  pod 'AlamofireImage'

end
